// <auto-generated />
using System;
using IpiPro.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpiPro.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626185559_AddDiscrepancyResolutionFields")]
    partial class AddDiscrepancyResolutionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IpiPro.Api.Models.CheckInEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecimenId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("ManifestId");

                    b.HasIndex("SpecimenId");

                    b.ToTable("CheckInEvents");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Discrepancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SpecimenId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("ManifestId");

                    b.HasIndex("SpecimenId");

                    b.ToTable("Discrepancies");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Lab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Labs");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Manifest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("LabId");

                    b.ToTable("Manifests");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Specimen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LabId")
                        .HasColumnType("int");

                    b.Property<int>("ManifestId")
                        .HasColumnType("int");

                    b.Property<string>("Patient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LabId");

                    b.HasIndex("ManifestId");

                    b.ToTable("Specimens");
                });

            modelBuilder.Entity("IpiPro.Api.Models.CheckInEvent", b =>
                {
                    b.HasOne("IpiPro.Api.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IpiPro.Api.Models.Manifest", "Manifest")
                        .WithMany("CheckInEvents")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IpiPro.Api.Models.Specimen", "Specimen")
                        .WithMany()
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lab");

                    b.Navigation("Manifest");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Clinic", b =>
                {
                    b.HasOne("IpiPro.Api.Models.Lab", "Lab")
                        .WithMany("Clinics")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Discrepancy", b =>
                {
                    b.HasOne("IpiPro.Api.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IpiPro.Api.Models.Manifest", "Manifest")
                        .WithMany("Discrepancies")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IpiPro.Api.Models.Specimen", "Specimen")
                        .WithMany()
                        .HasForeignKey("SpecimenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Manifest");

                    b.Navigation("Specimen");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Manifest", b =>
                {
                    b.HasOne("IpiPro.Api.Models.Clinic", "Clinic")
                        .WithMany("Manifests")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IpiPro.Api.Models.Lab", "Lab")
                        .WithMany("Manifests")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Specimen", b =>
                {
                    b.HasOne("IpiPro.Api.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IpiPro.Api.Models.Manifest", "Manifest")
                        .WithMany("Specimens")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lab");

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Clinic", b =>
                {
                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Lab", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("IpiPro.Api.Models.Manifest", b =>
                {
                    b.Navigation("CheckInEvents");

                    b.Navigation("Discrepancies");

                    b.Navigation("Specimens");
                });
#pragma warning restore 612, 618
        }
    }
}
